name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read version
        id: get_version
        run: echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/timezone-app:${{env.VERSION}} .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/timezone-app:${{env.VERSION}}

      - name: Checkout deployment repo
        uses: actions/checkout@v4
        with:
          repository: jbaravinda/timezone-deploy
          token: ${{ secrets.GH_PAT }}
          # path: /

      - name: Update Kubernetes manifests
        run: |
          cd k8s
          sed -i 's|image: ${{ secrets.DOCKERHUB_USERNAME }}/timezone-app:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/timezone-app:${{env.VERSION}}|g' deployment.yaml
          git config user.name "jbaravinda"
          git config user.email "jbaravindadiascis@gmail.com"
          git add .
          git commit -m "Update image to latest version"
          git push
